version: "3.7"

services:
        scraper:
                build: scraper/
                image: oxhack-scraper

        visual:
                build: visual/
                image: oxhack-visual
                ports:
                        - "8080:80"
